version: '3'
services:
    postfix:
        image: boky/postfix
        container_name: ada
        restart: always
        ports:
        - "25:587"
        volumes:
        - postfix-spool:/var/spool/postfix
        - postfix-etc:/etc/postfix
        - postfix-keys:/etc/opendkim/keys
        environment:
            ALLOWED_SENDER_DOMAINS: "play.satswala.com"
            POSTFIX_hostname: "play-satswala"
            TZ: "Asia/Kolkata"
            DKIM_SELECTOR: "play"
        networks:
        - stackmate-network

volumes:
    postfix-spool:
    postfix-etc:
    postfix-keys:

networks:
    stackmate-network:
        driver: bridge
    
          

      